// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfvzZWmMeoxOXaFCgCdpp8DzHGBSFOT4c',
    appId: '1:803689424997:web:00594ef182a761e1593e8c',
    messagingSenderId: '803689424997',
    projectId: 'chat-app-8a27b',
    authDomain: 'chat-app-8a27b.firebaseapp.com',
    storageBucket: 'chat-app-8a27b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_2-2q3HI0zgDQJdSwHXlQ43rXjVOpj2E',
    appId: '1:803689424997:android:0a0e1e93387f0498593e8c',
    messagingSenderId: '803689424997',
    projectId: 'chat-app-8a27b',
    storageBucket: 'chat-app-8a27b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtHoFP-vwvrEL8-DPVgOQ9Yh1siIdGgpE',
    appId: '1:803689424997:ios:212dac5e0da2d024593e8c',
    messagingSenderId: '803689424997',
    projectId: 'chat-app-8a27b',
    storageBucket: 'chat-app-8a27b.appspot.com',
    iosClientId: '803689424997-o79ksvj735op8g04jhet9kt81de1n33r.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtHoFP-vwvrEL8-DPVgOQ9Yh1siIdGgpE',
    appId: '1:803689424997:ios:a470a912f221d2d2593e8c',
    messagingSenderId: '803689424997',
    projectId: 'chat-app-8a27b',
    storageBucket: 'chat-app-8a27b.appspot.com',
    iosClientId: '803689424997-clq0jg1mtt4dgrklt60dbbtrn208g93h.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
